program: src/my_project/train.py
name: sweepdemo
project: my_awesome_project
entity: s234803-danmarks-tekniske-universitet-dtu
method: random
metric:
    goal: minimize
    name: validation_loss
parameters:
    learning_rate:
        min: 0.0001
        max: 0.1
        distribution: log_uniform
    batch_size:
        values: [16, 32, 64]
    epochs:
        values: [5, 10, 15]
run_cap: 10