name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ["windows-latest"]
        python-version: ["3.11"]

    steps:
      - name: Get data
      - run: dvc pull

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements_tests.txt
          pip install -r requirements.txt
          pip list

      - name: Test with coverage
        run: |
          coverage run -m pytest -v # Run tests with coverage measurement
          coverage report
